name: CI + CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: echo Compiling build
      # Here is where unit tests will be run, so the pipeline will stop if the build fails

  DeployDev:
    name: Deploying to Development
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: "http://dev.placeholderurl.com"
    steps:
      - name: Deploy
        run: echo Deploying to dev

  DeployStaging:
    name: Deploying to Staging
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: "http://test.placeholderurl.com"
    steps:
      - name: Deploy
        run: echo Deploying to staging

  DeployProd:
    name: Deploying to Production
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: "http://www.placeholderurl.com"
    steps:
      - name: Deploy
        run: echo Deploying to prod
